runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Set store path
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path | tr -d '\n')" >> $GITHUB_ENV

    - uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm

    - name: Set store path
      run: pnpm install
      shell: bash
