app = "cool-frost-5501"
primary_region = "yul"

[build]
image = "milesmcc/shynet:v0.13.1"

[env]
ACCOUNT_SIGNUPS_ENABLED = "False"
AGGRESSIVE_HASH_SALTING = "True"
ALLOWED_HOSTS = "stats.kimchiii.space"
BLOCK_ALL_IPS = "False"
CSRF_TRUSTED_ORIGINS = "https://stats.kimchiii.space"
DB_NAME = "/var/local/shynet/db/db.sqlite3"
LANGUAGE_CODE = "en-ca"
LOCATION_URL = "https://www.openstreetmap.org/?mlat=$LATITUDE&mlon=$LONGITUDE"
SCRIPT_USE_HTTPS = "True"
SHOW_SHYNET_VERSION = "True"
SHOW_THIRD_PARTY_ICONS = "False"
SQLITE = "True"
TIME_ZONE = "America/Toronto"

[http_service]
force_https = true
internal_port = 8080

[mounts]
destination = "/var/local/shynet/db"
source = "shynet_data"

initial_size = "1gb"

[[vm]]
cpus = 1
cpu_kind = "shared"

memory = "1gb"
