name: CI

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' &&
    github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  ASTRO_TELEMETRY_DISABLED: 1
  NODE_OPTIONS: "--max_old_space_size=4096"

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  lint-then-format:
    name: Lint and format code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run ESLint
        run: bun run lint

      - name: Run Prettier
        if: ${{ success() }}
        run: bun run format
