name: CI

on:
  push:
    branches: [main]
  merge_group:
  pull_request:
    branches: [main]

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' &&
    github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: "--max_old_space_size=4096"

jobs:
  astro-check:
    name: Check for type issues with `astro check`
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install step
        uses: ./.github/actions/install

      - name: Run check
        run: pnpm run check
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install step
        uses: ./.github/actions/install

      - name: Run check
        run: pnpm run lint:eslint
