name: CI

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' &&
    github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: "--max_old_space_size=4096"

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  lint:
    name: Linting (cspell, markdownlint, eslint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install step
        uses: ./.github/actions/setup

      - name: ✂️ Run knip
        run: pnpm run knip

      - name: Run cspell
        run: pnpm run lint:spell

      - name: Run markdownlint
        run: pnpm run lint:md

      - name: Run eslint
        run: pnpm run lint
