name: "Format code using Prettier"

on:
  push:
    branches: [main]
  merge_group:
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      # Give the default `GITHUB_TOKEN` write permission to commit and push the
      # added or changed files to the repository
      contents: write
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - name: Check out code using Git
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install step
        uses: ./.github/actions/install

      - name: Format code
        run: pnpm run format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[ci] format"
          branch: ${{ github.head_ref }}
          commit_user_name: fredkbot
          commit_user_email: fredk+bot@github.com
